### ISSUE TITLE
no readme

### ISSUE THREAD

**Issue by ryleu** [Moulberry/Graphite#1]
a README.md is a great way to tell people what the heck your project is, how to help build it, and how to test what you’ve made. once you’re at the point where others can help, i’d highly recommend making one

**Comment by Moulberry** [comment]
Thanks for your interest in this project

I will create a readme once the software has been developed some more
Currently the only thing Graphite is able to do is send you a [server list ping](https://wiki.vg/Server_List_Ping)

Most likely I will create the readme once you are able to fully connect with a Minecraft client
Until then, I'll leave this issue open

**Comment by GalaxyLPS** [comment]
Commit 1ee571d67be362517882a3b117bae5bb88778ee1 is stating, that you are now able to join a server. Its a great time for adding a README. Not only will your project look more mature but also other people might want to join and help you, and by adding a README (with the right contents) you will give them the opportunity to do so.

**Comment by Moulberry** [comment]
Readme has been added
