### ISSUE TITLE
Transmute between `Vec` types in graphite NBT

### ISSUE THREAD

**Issue by rj00a** [Moulberry/Graphite#7]
In `crates/graphite_binary/src/nbt/decode.rs` there is this
```rust
let vec: Vec<u8> = arr_bytes.into();
Ok(unsafe { std::mem::transmute(vec) })
```
Transmuting between `Vec` types is incorrect because `#[repr(Rust)]` types make no guarantee about their layout. The Rustonomicon has this to say:

> So how do you know if the layouts are the same? For repr(C) types and repr(transparent) types, layout is precisely defined. But for your run-of-the-mill repr(Rust), it is not. Even different instances of the same generic type can have wildly different layout. Vec\<i32> and Vec\<u32> _might_ have their fields in the same order, or they might not. The details of what exactly is and is not guaranteed for data layout are still being worked out over [at the UCG WG](https://rust-lang.github.io/unsafe-code-guidelines/layout.html).

**Comment by Moulberry** [comment]
Fixed by 8c6f60c
